### PR TITLE
VCluster

### PR DESCRIPTION
**Pull request by Antoine-BL**
### Description
Deploiement de VCluster via ArgoCD.

### Related Issue
#6 
#7 

### Testing Procedure
N/A

### Checklist

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

- [x] Requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Antoine-BL** [comment]
Docs
https://github.com/ClubCedille/wiki.cedille.etsmtl.ca/pull/9

**Review by mj-sakellaropoulos — APPROVED** [review]

**Comment by Simon-Boyer** [comment]
We need to enable storage classes sync: https://www.vcluster.com/docs/storage

**Comment by Simon-Boyer** [comment]
We also need to have ingress sync. We should be able to have different base domains for different vclusters, maybe deploying the cert-managers inside each vclusters instead of system wide? To explore

**Comment by Simon-Boyer** [comment]
@ThomasCardin also on dirait ils supportent pas encore le gateway api... https://github.com/loft-sh/vcluster-plugins/issues/35

**Pull request closed without merging**
